### ISSUE TITLE
Add lint workflow

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#29]
for example

```
name: Lint Python
on: [push]
jobs:
  call-run-python-linters:
    uses: openclimatefix/.github/.github/workflows/python-lint.yml@main
```

Various code changes might need to happen due to this
